import { Header } from "components/common/Header";
import { ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

export function AboutPage() {
    return (
        <SafeAreaView>
            <ScrollView>
                <Header title="About MTheke" />
                <View className="flex-1 justify-center items-center p-4">
                    <Text className="text-white">
                        MTheke is a mobile app that allows you to search and watch videos from various media libraries.
                        The libraries are provided by public broadcasters and other media companies in Germany mostly.
                        {"\n\n"}
                        The app is free and open-source. You can find the source code on GitHub.
                        {"\n\n"}
                        The list of movies is generated by parsing the RSS feeds provided by
                        {"\n\n"}
                        https://mediathekviewweb.de
                        {"\n\n"}


                    </Text>
                </View>
            </ScrollView>
        </SafeAreaView>
    )
}