import { ExternalLink } from "components/common/ExternalLink";
import { Header } from "components/common/Header";
import { ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

export function AboutPage() {
    return (
        <SafeAreaView>
            <ScrollView>
                <Header title="About MTheke" color="text-red-500"/>
                <View className="flex-1 justify-center items-center p-4 gap-4">
                    <Text className="text-white">
                        MTheke is a mobile app that allows you to search and watch videos from various media libraries.
                        The libraries are provided by public broadcasters and other media companies in Germany mostly.
                        {"\n\n"}
                        The app is free and open-source. You can find the source code on GitHub. 
                        Written by Stepan Rutz (stepan.rutz AT stepanrutz.com)
                    </Text>
                    <ExternalLink url="https://github.com/srutz/mtheke" label="GitHub Project Page" />
                    <Text className="text-white">
                        The list of movies is generated by parsing the RSS feeds provided by
                    </Text>
                    <ExternalLink url="https://mediathekviewweb.de" label="MediathekViewWeb" />
                    <Text className="text-white">
                        No data is stored on any server and no tracking is performed by this app. 
                        Requests to mediathekviewweb.de are subject ot the privacy policy of that website.
                        The Streams are played directly from the media libraries.
                    </Text>
                </View>
            </ScrollView>
        </SafeAreaView>
    )
}